### ISSUE TITLE
STS: Mongodb goes into `CrashLoopBackOff`

### ISSUE THREAD

**Issue by surajssd** [Azure-Samples/aks-store-demo#197]
**Describe the bug**

I installed the app using [aks-store-all-in-one.yaml](https://github.com/Azure-Samples/aks-store-demo/blob/main/aks-store-all-in-one.yaml) config but the mongodb pod goes into `CrashLoopBackOff` because its liveness probe fails. Liveness check is failing with the following error:

`pets          0s          Warning   Unhealthy                 pod/mongodb-0                            Liveness probe failed: OCI runtime exec failed: exec failed: unable to start container process: exec: "mongosh": executable file not found in $PATH: unknown`

**To Reproduce**
1. Follow steps from: https://github.com/Azure-Samples/aks-store-demo/tree/main?tab=readme-ov-file#run-on-any-kubernetes i.e.:

```bash
kubectl create ns pets

kubectl apply -f https://raw.githubusercontent.com/Azure-Samples/aks-store-demo/main/aks-store-all-in-one.yaml -n pets
```

2. Run the following to see that the `mongodb-0` pod keeps restarting:

```bash
kubectl get events -w -n pets
```
**Expected behavior**

Pod should pass the liveness probe.

**Source of the error**

https://github.com/Azure-Samples/aks-store-demo/blob/5712ff53031f8e8b0667ac8fdca0f9b6fcf37a53/aks-store-all-in-one.yaml#L32-L36

**Comment by pauldotyu** [comment]
@surajssd what type of kubernetes cluster were you running this on?

**Comment by surajssd** [comment]
@pauldotyu I was using Minikube.

But this seems like an issue regardless of the k8s kind. This looks like a container image issue.

**Comment by ITOpenwork** [comment]
The following settings seem to work good in minikube:
```
        livenessProbe:
          exec:
            command:
            - mongosh
            - --eval
            - db.runCommand('ping').ok
          initialDelaySeconds: 30
          periodSeconds: 20
          timeoutSeconds: 10
          failureThreshold: 6
          successThreshold: 1
```
